import * as fa from "react-icons/fa/index.js";
import * as io  from "react-icons/io/index.js";
import * as io5 from  "react-icons/io5/index.js";
import * as md  from "react-icons/md/index.js";
import * as ti  from "react-icons/ti/index.js";
import * as go from "react-icons/go/index.js";
import * as fi from "react-icons/fi/index.js";
import * as gi from "react-icons/gi/index.js";
import * as wi from "react-icons/wi/index.js";
import * as di from "react-icons/di/index.js";
import * as ai from "react-icons/ai/index.js";
import * as bs from "react-icons/bs/index.js";
import * as ri from "react-icons/ri/index.js";
import * as fc from "react-icons/fc/index.js";
import * as gr from "react-icons/gr/index.js";
import * as hi from "react-icons/hi/index.js";
import * as si from "react-icons/si/index.js";
import * as im from "react-icons/im/index.js";
import * as bi from "react-icons/bi/index.js";
import * as cg from "react-icons/cg/index.js";
import * as vsc from "react-icons/vsc/index.js";

export {fa, io, io5, md, ti, go, fi, gi, wi, di, ai, bs, ri, fc, gr, hi, si, im, bi, cg, vsc};
